services:
  db:
    image: postgres:16.0-alpine
    env_file:
      - ./.env
    expose:
      - "5432"
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ./dbdata:/var/lib/postgresql/data

  redis:
    image: redis
    expose:
      - "6379"
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./redis/redisData:/data
